services:
  - type: web
    name: UlkaEnterprises
    env: java
    branch: main
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/UlkaEnterprises-0.0.1-SNAPSHOT.jar
    plan: free